---
server:
    packages:
      - curl
      - wget
      - ca-certificates
      - build-essential
      - libxml2-dev
      - unzip
      - git
      - zsh
    timezone: America/New_York
    locale: en_US.UTF-8
vagrant_local:
    vm:
      base_box: 'ubuntu/bionic64'
      hostname: travelfunds.core.vm
      ip: 192.168.80.13
      memory: 4096


postgresql_databases:
  - name: travelfunds

postgresql_users:
  - name: vagrant
