---
server:
    packages:
      - curl
      - wget
      - ca-certificates
      - build-essential
      - libxml2-dev
      - unzip
      - git
      - zsh
    timezone: America/New_York
    locale: en_US.UTF-8
vagrant_local:
    vm:
      base_box: 'ubuntu/bionic64'
      hostname: travelfunds.core.vm
      ip: 192.168.80.13
      memory: 8192

# this is "C.UTF-8" for compatiblity with the existing production DB.
# It may need to be changed to "en_US.UTF-8" in the future if this setting causes problems
pg_lc_collate: C.UTF-8

postgresql_databases:
  - name: travelfunds
    lc_collate: "{{ pg_lc_collate }}"
  - name: travelfunds-test
    lc_collate: "{{ pg_lc_collate }}"

postgresql_users:
  - name: vagrant
