---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: 'install python2.7 for ansible to use'
      raw: sudo apt-get update && sudo apt-get -y install python

- hosts: all
  become: true
  vars_files:
    - vars/all.yml
  roles:
    - { role: server, tags: ['server'] }
    - { role: vagrant_local, tags: ['vagrant_local'] }
